### ISSUE TITLE
How to collate/combine output data

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/reproducibility_study#28]
Each engine-specific project.py file will create simulation/analysis output, how should we combine all these outputs?
Some discussion about using zenodo: Would we just upload each job directory (as the hashed name will be the same across systems) as a separate entry to zenodo?

**Comment by justinGilmer** [comment]
Zenodo does let you mark and upload datasets in a different way compared to a github repo. Although each dataset is limited to 50GB. But we can upload as many datasets as we need to support this. See [the help/FAQ page for additional info](https://help.zenodo.org/)

Each dataset will get its own zenodo doi. I will play around and see if I can make a few archived versions of our workspace later and try to merge them. I do not forsee this becoming an issue though. Especially since each dataset will be focused on different workspace statepoints anyway.

**Comment by jennyfothergill** [comment]
OK, very cool! I see that on the zenodo website it is easy to upload a file, but I am not able to upload a folder. [This is a known issue](https://github.com/zenodo/zenodo/issues/1089).  It seems like the solution might be to zip the workspace folder. 
We should make sure to have a bash script or something similar to handle unzipping and syncing the workspaces.

**Comment by tcmoore3** [comment]
This is something we should push back until we're actually ready to upload our dataset.
