### ISSUE TITLE
Signac Flow Job Labels

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/reproducibility_study#43]
We need to be consistent with labeling our jobs if we're going to have a singular combined workspace. Speaking with @justinGilmer and @daico007, there might be a few ways to address this:

1. A simple method would be to use boolean statements for checking if files exist. For example:
```python
>>> @Project.label
>>> def lammps_applied_ff(job):
>>>    return job.isfile("box.lammps") and (job.sp.simulation_engine == "lammps")
```
2. A second option could be to use signac label filtering syntax. I'm not an expert on that so I'll leave that up to someone else explaining how that might work, but that could also simplify things.

**Comment by jennyfothergill** [comment]
The different engines don't necessarily need to interact too much during simulation--each `project.py` file will only operate on jobs for it's respective engine. And since we will [sanitize/standardize the output files](https://github.com/mosdef-hub/reproducibility_study/projects/1#card-66677615) the analysis routines can simply check that the standard output files exist.
